### ISSUE TITLE
Krok späť

### ISSUE THREAD

**Issue by Witchery** [scholtz/covid-sk-api#1]
Pridanie možnosti "krok späť". Ak by niekoho v poslednom kroku napadlo, že v daný deň nemôže ísť na testovanie.  Nie každý asi vie používať prehliadačovú možnosť "krok späť".

**Comment by scholtz** [comment]
Na každej stránke od výberu pobočky až po registráciu v modrom okne je zmeniť výber, čo smeruje ako krok späť
