### ISSUE TITLE
Adresa miesta pobytu

### ISSUE THREAD

**Issue by Witchery** [scholtz/covid-sk-api#6]
Mala by byt asi adresa trvaleho pobytu podla OP, ako inak administrativny pracovnik overi spravnost adresy.

**Comment by scholtz** [comment]
Toto je otázka na osobu ktorá odosiela údaje hygiene, aké konkrétne údaje potrebuje. Zatiaľ mi k tejto veci oficiálne nebolo odpovedané. Ako hygiena by som skôr preferoval adresu kde sa zdržiava ako adresu trvalého bydliska čo je často rôzne..
